branches:
  only:
  - production
language: python
python:
- '2.7'
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "tay@taybird.com"
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- pip install -r requirements.txt
script:
- ./build
deploy:
  provider: s3
  region: us-west-2
  local_dir: static
  bucket: taybird-aboutme
  detect_encoding: true
  acl: public_read
  skip_cleanup: true
  secret_access_key:
    secure: FBfVrLU1/53sEXvbZULXNvShYyuHZtRj+4GzLkSAh9r+GG+Gfy819Lf5RJ7qdeOEm5Gav535UfkNmqHwYtm4yELe5VV4Z6lUzUe03TgK+M3oRRA3b4kegNCgnyODm1hUgp3X0y86vJ8fWMkFr7Vb8Rjvpw/0lUL5yExVoQErj7sXURWL+GigHLzU+kqylNynSIkI+BcfVwdv/LfwA8mPotZJjvFh6hsvgwFEZxIVq8sYEd99Ygs1AgPC1Im1vImRNN4IDXpUpPhb4vkTt1Hb3+37iKk0HR0hzyt5GimnvLJLZz7a7KTmvBIF+tlUg5JHrfbPS5UUrIcZuPLN2EuJsWaFMqxsYO/8zCC6oiU6uSgqvgl73bEqqRouEs0X62JGI40l/B3kzaIeJ9Sl6/jLyfD4Oxxo0NKQVFmHlMJVtWr7dmVsSR6Zmgw88jddw3Nb4Cx4y9xeLwiq7bAbXQJxebASWwzJ010j4Oc1NOvpwW82cBIGUUSTSwWUOX2dEANUxlnBFYbWJdRgpverM9tMF/K08rxwpRiwaE+3Es+831faviyIKeB54qlA7TxLZwsZXlTHZcPWOPTRcUxwZS98QM7CIDdOjgGlZ2PFOATck4JT85nuCvy+FWDPOLFaKNQF1ejLLytvdRQM/Q1iVuJLZOsSlQl2RXJvEgdVH5ngC2M=
  access_key_id:
    secure: kDR+jl3h8XVncSlGk5+ePpOtCQPHEVEG8Xqq6+yDhuwJ4CYGgB8z5HrWjyAZD1OJo1Z5H9b+iRbAOYERar1r7KpRJMThGnf1wtO3JgddBLOHDY80w0fhA0jHVe3qHwrLFXieemvTqv92BI+3+YGIy6KEhXCSiznBFY1ZbhjXLZrhkwA3lfCsD2i3XbGAxxAa5ASs8zq2NwcvbevPnKgFAFRx+XcktDiLndUfbsM7ubF0g4oyjUp0xijcs/fcFCzEsN3/dON9PEiQNOQKrVNAyQFNs0bLbakSavX/rUF2L/Er1XkqAobI3lUS1cOBHGtaZIbzwGmJ6EOAx6404Dwdzcqf4DmfPhm/1Uc8Z1Y9W2p0qzNO7chXZdnTo4ioP8fPdPGR7T6p2r25NTETXYsmKSCKAUR9eQ5/7gc33E2ha3pfDQeNevK5/fXXgnCifrxqPuhFxMkNsAZjpiljCCnryR5VCV3ZTn3zxhnFSoeR664rOHqXpA/tBFeZlxfBw4ojOWQUP3snYbgqgRLPCAvxmU38DAQntCSK1n3NxyGYZrScd+aHyCcOMYaFgd9rlVaDrc4kfWzV/VuBPSqqC88kCQExxdk3xpOi7nPEth1h9PW7BvRlsN7W91SbJwF4at7C/u0YORbqZuVnpzQOlH4E5R+9cS3caZG0ACvZzOiZB48=
