branches:
  only:
  - production
language: python
python:
- '2.7'
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "tay@taybird.com"
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
deploy:
  provider: s3
  region: us-west-2
  local_dir: html
  bucket: taybird-birdnest
  detect_encoding: true
  acl: public_read
  skip_cleanup: true
  access_key_id:
    secure: HxgWyRdIFoflBv1BC7bc0S09QbFH7rk9P1edJWieQOlndq14HWPQRPQMmk4VZJ8HQkLNe+DgcjzE+oQaXRvCojlJFQ7N6lEX2IpbV5Cc08M5H4cC99ssck90GLuXuzCf3yPQ32NopqdlJUEOrINMLBi35GdyEpo1v07D6WivmeSyPRk8I1S5ODNWnnnJX1xAPet4sSCfvkSa70JunHTFOKx0TsfPMRRHBJAm+R3QhpbVjIrKTAWpmpQ54Nn/0Xfil1+k5CexBnV+4u7thujNSk65D5aj9eTVvmoOgqtAiOaIhs4r3DcJzfnKIYMnMHuGonvq5xiPa/lGixBHUGjV3VjdJaqDiaEsHN7AqYIj00e67IDvXzAXu8U9yE2g/I0DniDrnlou9l1Q9XXDlLRPn87nXcnrVGZIhjia7G0auEIxsvYhlMZYMHC1nNOIxlAjC8ng3dd5zTHExh1jebcFIb8hzYLH3DEN4ClwiLcM0BGC00IQRClpb6wadEhfs9sszMGOe1LjSeJf/K0T1Tv6HSdW3J5cLK+c5gQOnL6GkAcjhfqohOfd9rkgQ5x8VWGjpy2a7o02LyVSW1VtAq7N9MJ0IBlxzEPWt5Jt2oleE7PQY6+rvqXO0TOPL+VWYiivwVGIeVkauor+RIhdhKhcPEB5oLqpGez1lUhZEVI4fic=
  secret_access_key:
    secure: Otkrn0Bm2N3au2ikN4jbwAx/6ZN2uc5JVSpC04twQCqCGx3PmYNFZBVpvMW7A/dRevb+bUcYrCBzXQwnDrFbFLkNpUB7JezIkh5JX8cwSFdK59HwK2wYIoMAP+BdUaFhK/qd+Q74B+LUk+U3MDjH6zCd/NnBDDx+cHyxbCsD1iKXAbYzZtEDfvwXbJV3eoLfwK4+40edUHJFeF9ffJ4sDd9K1fmwrDxVcHUAWCy7Nc8N/h/goCShHmCQlmRYdkyVJZsNuLPJvKoBrhPwbxp/WOHdVvzM+18adGrlLvyUo1xD+ZKpAf/Su/WaucwYxHd5eUkF4Q7OodQzdd6K0DHBr3Bf3ns9QNngPvgk59WNt+Ppr2lUwsFT882Pyf6NbgjVFG6IaA1kEsCVvdlR69Z362tJzYED6vWn60PPKBv1gvV5PvYkvFClT+W9IQcTP6VZF8ZiDkUSle5R0XDisezcbvnEzZPuZpOwL73hePBGlhuEle3BvXHUBIdogS0zGFooEgENShO+BkgWV7lfnMJkgvQBLV6FfLwrjmX9+VGQdO8sQF2HgZlfCnZPZiSoDwZvUlbdzmjdBWcabodBD3Lw4/Z0KI4vjFlvAAaOdSSqO9YAoUJMVflWgnlPbeUcwyTixOFRb+xC/r3nyiku9HdszDaQ8JMh0aWzAsle5AzKjg8=
